### ISSUE TITLE
Link: no target available for "#understudies"

### ISSUE THREAD

**Issue by pvosper** [theodox/ta_101#2]
In the line "conversation with the understudy on the code", the word "understudy" is linked to:

https://github.com/theodox/ta_101/blob/master/TA%20coding%20101.md#understudies

This link does not take the user anywhere.

**Comment by pvosper** [comment]
This should probably link to "Working together" (this is a brilliant idea, btw)

**Comment by theodox** [comment]
It's supposed to have an anchor, I'll double check that.

**Comment by theodox** [comment]
It's pointing right, does not seem to work inside of github view :(

**Comment by iancarnation** [comment]
Perhaps the markdown renderer you're using is more forgiving??  Looks like putting 
`<a id="understudies"></a>` near the 'Working Together' header will make the `[understudy](#understudies)` link work. The Markdown Syntax page uses that syntax itself if you want to see it for fun: https://daringfireball.net/projects/markdown/syntax.text

I was actually going to add those for my next little PR :)
